### ISSUE TITLE
markdown not rendering the same on GitHub and CYLGame

### ISSUE THREAD

**Issue by pahp** [UMDLARS/CYLGame#25]
The following code renders differently on GitHub than CYLGame:

```
# Accessing Game Data

Robot has access to the following information:
 * variables -- variables that tell you about general game state
 * automatic sensors -- things that change depending on where you are
 * the map array -- the entire play field
```

Here's what it looks like on GitHub:

![image](https://user-images.githubusercontent.com/15266857/40326917-977add68-5d06-11e8-8601-ddecd01a5b5e.png)

Here's what it looks like in CYLGame:

![image](https://user-images.githubusercontent.com/15266857/40326937-aaba6f10-5d06-11e8-9704-684e0a62b0d1.png)

**Comment by pahp** [comment]
Adding a blank line before the bulleted list fixed it:

![image](https://user-images.githubusercontent.com/15266857/40327049-12b80424-5d07-11e8-8f28-14d1f0338e25.png)

... still, I think the rendering should be the same or there will be regular formatting issues like this.

**Comment by ChandlerSwift** [comment]
Not sure if this is something you were aware about nor if it's practical for use here, but I recently found out that GitHub exposes an API for rendering markdown using its rules (which apparently vary slightly from the commonmark spec?): https://developer.github.com/v3/markdownIf it's a priority to render the .md files exactly like GitHub does, this could be an option (or at least something to test against).On May 21, 2018 2:56 PM, "Peter A. H. Peterson" <notifications@github.com> wrote:Adding a blank line before the bulleted list fixed it:

... still, I think the rendering should be the same or there will be regular formatting issues like this.

**Comment by pahp** [comment]
Given all the other real issues on this list, I'm going to close this one. It's just not very important.
